jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Node4:
        NODE_VERSION: '4.x'
      Node6:
        NODE_VERSION: '6.x'    
      Node8:
        NODE_VERSION: '8.x'
      Node10:
        NODE_VERSION: '10.x'        
      NodeLatest:
        NODE_VERSION: '>10.x'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)
        checkLatest: 'true'
      displayName: 'Install Node.js'
    - script: |
        npm install
      displayName: 'npm install'
    - script: |
        npm run test-cov
      displayName: 'npm test'
    - script: |
        npm install -g codecov
        codecov
        cat ./coverage/lcov.info | coveralls
      displayName: 'codecov and coveralls'      
#TODO: Webhooks for gitter

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Node8:
        NODE_VERSION: '8.x'
      Node10:
        NODE_VERSION: '10.x'        
      NodeLatest:
        NODE_VERSION: '>10.x'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)
        checkLatest: 'true'
      displayName: 'Install Node.js'
    - script: |
        npm install
      displayName: 'npm install'
    - script: |
        istanbul cover tape node_modules/tape/bin/tape.js tests/test-*.js
      displayName: 'npm test'
